<?php
use PHPUnit\Framework\TestCase;

class AddToWishlistTest extends TestCase
{
    public function testAddToWishlistSuccess()
    {
        // Mock the necessary session data and $_GET parameters
        $_SESSION['username'] = 'testuser';
        $_GET['book_id'] = 123; // Replace with a book ID that you want to add to the wishlist

        // Start output buffering to capture the script's output
        ob_start();

        // Include the 'add-to-Wishlist.php' script
        require 'add-to-Wishlist.php';

        // Capture the output (JSON response) generated by the script
        $output = ob_get_clean();

        // Assertions to check if the response is as expected
        $expectedResponse = [
            "status" => "success",
            "message" => "Book added to your wishlist successfully."
        ];

        $this->assertJsonStringEqualsJsonString(json_encode($expectedResponse), $output);
    }
}
?>