trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    sudo apt-get update
    sudo apt-get install -y php php-mysql mysql-server
    sudo service mysql start
    sudo mysql -e "CREATE DATABASE IF NOT EXISTS bookonlineorder;"
    sudo mysql -e "GRANT ALL PRIVILEGES ON bookonlineorder.* TO 'root'@'localhost' IDENTIFIED BY '';"
    sudo mysql -e "FLUSH PRIVILEGES;"
    wget https://phar.phpunit.de/phpunit-9.6.13.phar
    chmod +x phpunit-9.6.13.phar
    sudo mv phpunit-9.6.13.phar /usr/local/bin/phpunit
  displayName: 'Setup environment'

- script: |
    phpunit ./Test/deleteProductTest.php
  displayName: 'Run PHPUnit Test'
