trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: sudo apt-get update && sudo apt-get install -y mysql-server
  displayName: 'Install MySQL'

- script: |
    sudo service mysql start
    sudo mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED BY 'RootPass123!';"
    sudo mysql -e "CREATE USER IF NOT EXISTS 'testuser'@'localhost' IDENTIFIED BY 'TestPass123!';"
    sudo mysql -e "CREATE DATABASE IF NOT EXISTS bookonlineorder;"
    sudo mysql -e "GRANT ALL ON bookonlineorder.* TO 'testuser'@'localhost';"
    sudo mysql -e "FLUSH PRIVILEGES;"
  displayName: 'Setup MySQL'

- script: |
    sudo apt-get install -y php php-mysqli
    wget -O phpunit https://phar.phpunit.de/phpunit-9.phar
    chmod +x phpunit
  displayName: 'Install PHPUnit'

- script: ./phpunit --verbose ./Test/deleteProductTest.php
  displayName: 'Run deleteProductTest'

