trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
  
- script: |
    sudo apt-get update
    sudo apt-get install -y php
    wget https://phar.phpunit.de/phpunit-9.6.13.phar
    chmod +x phpunit-9.6.13.phar
    sudo mv phpunit-9.6.13.phar /usr/local/bin/phpunit
  displayName: 'Install PHP and PHPUnit'

- script: |
    phpunit ./Test/addBookTest.php
    phpunit ./Test/AddToCartTest.php
    phpunit ./Test/DeleteBookTest.php
    phpunit ./Test/deleteProductTest.php
    phpunit ./Test/EditBookTest.php
    phpunit ./Test/UpdateCartTest.php
  displayName: 'Run PHPUnit Tests'
