trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Pipeline successful
  displayName: 'Run a test'
#comment

# trigger:
# - main

# pool:
#   vmImage: 'ubuntu-latest'

# steps:
# - task: UsePythonVersion@0
#   inputs:
#     versionSpec: '3.x'
#     addToPath: true

# - script: |
#     sudo apt-get update
#     sudo apt-get install mysql-client -y
#     sudo apt-get install mysql-server -y
#     mysql --host=localhost --user=root --password="" -e 'USE bookonlineorder; source database.sql'
#   displayName: 'Execute SQL script'
#   env:
#     database_host: "localhost"
#     database_user: "root"
#     database_password: ""