trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: sudo apt-get update && sudo apt-get install -y mysql-server
  displayName: 'Install MySQL'

- script: |
    sudo service mysql start
    sudo mysql -e "CREATE USER IF NOT EXISTS 'testuser'@'127.0.0.1';"
    sudo mysql -e "CREATE DATABASE IF NOT EXISTS bookonlineorder;"
    sudo mysql -e "GRANT ALL ON bookonlineorder.* TO 'testuser'@'127.0.0.1';"
    sudo mysql -e "FLUSH PRIVILEGES;"
    sudo mysql -e "SELECT user, host FROM mysql.user;"
  displayName: 'Setup MySQL'

- script: |
    sudo apt-get install -y php php-mysqli
    wget -O phpunit https://phar.phpunit.de/phpunit-9.phar
    chmod +x phpunit
  displayName: 'Install PHPUnit'

- script: ./phpunit --verbose ./Test/deleteProductTest.php
  displayName: 'Run deleteProductTest'

