# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- script: |
    /opt/homebrew/bin/php /opt/homebrew/bin/phpunit-9.6.13.phar ./Test/addBookTest.php
    /opt/homebrew/bin/php /opt/homebrew/bin/phpunit-9.6.13.phar ./Test/AddToCartTest.php
    /opt/homebrew/bin/php /opt/homebrew/bin/phpunit-9.6.13.phar ./Test/DeleteBookTest.php
    /opt/homebrew/bin/php /opt/homebrew/bin/phpunit-9.6.13.phar ./Test/deleteProductTest.php
    /opt/homebrew/bin/php /opt/homebrew/bin/phpunit-9.6.13.phar ./Test/EditBookTest.php
    /opt/homebrew/bin/php /opt/homebrew/bin/phpunit-9.6.13.phar ./Test/UpdateCartTest.php
  displayName: 'Run PHPUnit Tests'
