trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
  
- script: |
    sudo apt-get update
    sudo apt-get install -y php php-mysql mysql-server expect
    wget https://phar.phpunit.de/phpunit-9.6.13.phar
    chmod +x phpunit-9.6.13.phar
    sudo mv phpunit-9.6.13.phar /usr/local/bin/phpunit
  displayName: 'Install PHP, MySQL, Expect and PHPUnit'

- script: |
    sudo service mysql start
    SECURE_MYSQL=$(expect -c "
    set timeout 10
    spawn mysql_secure_installation
    expect \"Press y|Y for Yes, any other key for No:\"
    send \"y\r\"
    expect \"New password:\"
    send \"\r\"
    expect \"Re-enter new password:\"
    send \"\r\"
    expect \"Remove anonymous users? (Press y|Y for Yes, any other key for No) :\"
    send \"y\r\"
    expect \"Disallow root login remotely? (Press y|Y for Yes, any other key for No) :\"
    send \"y\r\"
    expect \"Remove test database and access to it? (Press y|Y for Yes, any other key for No) :\"
    send \"y\r\"
    expect \"Reload privilege tables now? (Press y|Y for Yes, any other key for No) :\"
    send \"y\r\"
    expect eof
    ")
    echo "$SECURE_MYSQL"
    sudo mysql -u root -e "CREATE DATABASE IF NOT EXISTS bookonlineorder;"
    sudo mysql -u root -e "GRANT ALL PRIVILEGES ON bookonlineorder.* TO 'root'@'localhost';"
    sudo mysql -u root -e "FLUSH PRIVILEGES;"
  displayName: 'Start MySQL, Secure Installation and Create Test Database'

- script: |
    phpunit ./Test/addBookTest.php
    phpunit ./Test/AddToCartTest.php
    phpunit ./Test/DeleteBookTest.php
    phpunit ./Test/deleteProductTest.php
    phpunit ./Test/EditBookTest.php
    phpunit ./Test/UpdateCartTest.php
  displayName: 'Run PHPUnit Tests'
