# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# trigger:
# - main

# pool:
#   vmImage: ubuntu-latest

# steps:
# - script: echo Hello, world!
#   displayName: 'Run a one-line script'

# - script: |
#     echo Add other tasks to build, test, and deploy your project.
#     echo See https://aka.ms/yaml
#   displayName: 'Run a multi-line script'

# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    sudo apt-get update
    sudo apt-get install mysql-client -y
<<<<<<< HEAD
    mysql --host=$(database_host) --user=$(database_user) --password=$(database_password) -e 'USE bookonlineorder; source database.sql'
=======
    sudo apt-get install mysql-server -y
    mysql --host=localhost --user=root --password="" -e 'USE bookonlineorder; source database.sql'
>>>>>>> 1b50431a112bff4194bf5fedfe9cf03f79574637
  displayName: 'Execute SQL script'
  env:
    database_host: "localhost"
    database_user: "root"
    database_password: ""

