trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
  
- script: |
    sudo apt-get update
    sudo apt-get install -y php php-mysql mysql-server
    wget https://phar.phpunit.de/phpunit-9.6.13.phar
    chmod +x phpunit-9.6.13.phar
    sudo mv phpunit-9.6.13.phar /usr/local/bin/phpunit
  displayName: 'Install PHP, MySQL and PHPUnit'

- script: |
    sudo service mysql start
    sudo mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '';"
    sudo mysql -u root -e "CREATE DATABASE IF NOT EXISTS bookonlineorder;"
    sudo mysql -u root -e "GRANT ALL PRIVILEGES ON bookonlineorder.* TO 'root'@'localhost';"
    sudo mysql -u root -e "FLUSH PRIVILEGES;"
  displayName: 'Start MySQL and Create Test Database'

- script: |
    phpunit ./Test/addBookTest.php
    phpunit ./Test/AddToCartTest.php
    phpunit ./Test/DeleteBookTest.php
    phpunit ./Test/deleteProductTest.php
    phpunit ./Test/EditBookTest.php
    phpunit ./Test/UpdateCartTest.php
  displayName: 'Run PHPUnit Tests'
