trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: sudo apt-get update && sudo apt-get install -y mysql-server
  displayName: 'Install MySQL'

- script: |
    sudo service mysql start
    sudo mysql -e "CREATE USER IF NOT EXISTS 'testuser'@'localhost';"
    sudo mysql -e "CREATE DATABASE IF NOT EXISTS bookonlineorder;"
    sudo mysql -e "GRANT ALL ON bookonlineorder.* TO 'testuser'@'localhost';"
    sudo mysql -e "FLUSH PRIVILEGES;"
    # 这一行是新添加的，用于显示所有 MySQL 用户及其权限
    sudo mysql -e "SELECT user, host, authentication_string FROM mysql.user;"
  displayName: 'Setup MySQL'

- script: |
    sudo apt-get install -y php php-mysqli
    wget -O phpunit https://phar.phpunit.de/phpunit-9.phar
    chmod +x phpunit
  displayName: 'Install PHPUnit'

- script: ./phpunit --verbose ./Test
  displayName: 'Run tests'
